[platformio]
src_dir = Digital-Synth-PRA32-U2
default_envs = i2s_default

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
lib_deps =
  fortyseveneffects/MIDI Library@5.0.2
  adafruit/Adafruit GFX Library@^1.12.6
  adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
  adafruit/Adafruit TinyUSB Library
build_flags =
  -DUSE_TINYUSB

[env:i2s_default]
extends = env

[env:pwm_optional]
extends = env
board_build.f_cpu = 150000000L
build_flags =
  ${env.build_flags}
  -DPRA32_U2_USE_PWM_AUDIO_INSTEAD_OF_I2S

[env:uart_midi]
extends = env
build_flags =
  ${env.build_flags}
  -DPRA32_U2_USE_UART_MIDI
